- hosts: all
  vars:
    dynatrace_api_url: "{{ dynatrace_api_url }}"
    dynatrace_token: "{{ token }}"
    state: "{{ state }}"
  tasks:
#     - name: ensure nginx is at the latest version
#       apt: name=nginx state=latest
    - name: "update problem with comment before auto-remediation"
      when: state == "OPEN"
      uri:
        url: https://{{ dynatrace_api_url }}/api/v2/problems/{{ pid }}/comments?Api-Token={{ dynatrace_token }}
        method: POST
        body:
          comment: "Problem notification received by Ansible Tower.  Attempting to perform auto-remediation."
          message: "comment: Problem notification received by Ansible Tower.  Attempting to perform auto-remediation."
          user: "Job {{ tower_job_id }}"
          context: Ansible Tower
        body_format: json
        status_code: 200
    - name: restart nginx
      service:
          name: nginx
          state: restarted
    - name: "update problem with comment after remediation"
      when: state == "OPEN" 
      uri:
        url: https://{{ dynatrace_api_url }}/api/v1/problems/{{ pid }}/comments?Api-Token={{ dynatrace_token }}
        method: POST
        body:
          comment: "Successfully triggered auto-remediation."
          message: "Successfully triggered auto-remediation."
          user: "Job {{ tower_job_id }}"
          context: Ansible Tower
        body_format: json
        status_code: 200
